// Embedded initial seed metadata for Mobile Companion (6.7 KB)
// Contains all 20 tests and 3 categories without heavy desktop paperHtml
export const DEFAULT_MOBILE_DATA = {
  "folders": [
    {
      "id": "gate",
      "name": "GATE",
      "color": "#6366f1"
    },
    {
      "id": "go_classes",
      "name": "GO Classes",
      "color": "#10b981"
    },
    {
      "id": "nptel",
      "name": "NPTEL",
      "color": "#f59e0b"
    }
  ],
  "tests": [
    {
      "id": "1784718601555",
      "folderId": "gate",
      "title": "GATE CSE 2010 | Original Paper",
      "date": "2026-07-22",
      "marks": 48.67,
      "totalMarks": 100,
      "attempted": 55,
      "totalQs": 65,
      "correct": 39,
      "incorrect": 16,
      "notAttempted": 10,
      "duration": "180 Min",
      "timeTaken": "46.55 Min",
      "accuracy": "71%",
      "notes": "",
      "tags": [],
      "difficulty": "70",
      "session": "afternoon"
    },
    {
      "id": "1784718601556",
      "folderId": "gate",
      "title": "GATE CSE 2011 | Original Paper",
      "date": "2026-07-26",
      "marks": 56.66,
      "totalMarks": 100,
      "attempted": 48,
      "totalQs": 65,
      "correct": 40,
      "incorrect": 8,
      "notAttempted": 17,
      "duration": "180 Min",
      "timeTaken": "74.4 Min",
      "accuracy": "83%",
      "notes": "",
      "tags": [],
      "difficulty": "68",
      "session": "afternoon"
    },
    {
      "id": "1784718601557",
      "folderId": "gate",
      "title": "GATE CSE 2012 | Original Paper",
      "date": "2026-07-28",
      "marks": 70.33,
      "totalMarks": 100,
      "attempted": 54,
      "totalQs": 65,
      "correct": 47,
      "incorrect": 7,
      "notAttempted": 11,
      "duration": "180 Min",
      "timeTaken": "180m",
      "accuracy": "87%",
      "notes": "",
      "tags": [],
      "difficulty": "72",
      "session": "afternoon"
    },
    {
      "id": "1784718601558",
      "folderId": "gate",
      "title": "GATE CSE 2013 | Original Paper",
      "date": "2026-07-30",
      "marks": 59.33,
      "totalMarks": 100,
      "attempted": 48,
      "totalQs": 65,
      "correct": 39,
      "incorrect": 9,
      "notAttempted": 17,
      "duration": "180 Min",
      "timeTaken": "174m",
      "accuracy": "81%",
      "notes": "",
      "tags": [],
      "difficulty": "78",
      "session": "afternoon"
    },
    {
      "id": "1784718601559",
      "folderId": "gate",
      "title": "GATE CSE 2014 | Set 1 | Original Paper",
      "date": "2026-07-31",
      "marks": 55.67,
      "totalMarks": 100,
      "attempted": 47,
      "totalQs": 65,
      "correct": 38,
      "incorrect": 9,
      "notAttempted": 18,
      "duration": "180 Min",
      "timeTaken": "180m",
      "accuracy": "81%",
      "notes": "",
      "tags": [],
      "difficulty": "74",
      "session": "afternoon"
    },
    {
      "id": "1784718601560",
      "folderId": "gate",
      "title": "GATE CSE 2014 | Set 2 | Original Paper",
      "date": "2026-08-01",
      "marks": 61.67,
      "totalMarks": 100,
      "attempted": 50,
      "totalQs": 65,
      "correct": 42,
      "incorrect": 8,
      "notAttempted": 15,
      "duration": "180 Min",
      "timeTaken": "176m",
      "accuracy": "84%",
      "notes": "",
      "tags": [],
      "difficulty": "76",
      "session": "afternoon"
    },
    {
      "id": "1784718601561",
      "folderId": "gate",
      "title": "GATE CSE 2014 | Set 3 | Original Paper",
      "date": "2026-08-03",
      "marks": 73.33,
      "totalMarks": 100,
      "attempted": 55,
      "totalQs": 65,
      "correct": 49,
      "incorrect": 6,
      "notAttempted": 10,
      "duration": "180 Min",
      "timeTaken": "179m",
      "accuracy": "89%",
      "notes": "",
      "tags": [],
      "difficulty": "73",
      "session": "afternoon"
    },
    {
      "id": "1784718601562",
      "folderId": "gate",
      "title": "GATE CSE 2015 | Set 1 | Original Paper",
      "date": "2026-08-05",
      "marks": 76,
      "totalMarks": 100,
      "attempted": 57,
      "totalQs": 65,
      "correct": 50,
      "incorrect": 7,
      "notAttempted": 8,
      "duration": "180 Min",
      "timeTaken": "177m",
      "accuracy": "88%",
      "notes": "",
      "tags": [],
      "difficulty": "75",
      "session": "afternoon"
    },
    {
      "id": "1784718601563",
      "folderId": "gate",
      "title": "GATE CSE 2015 | Set 2 | Original Paper",
      "date": "2026-08-11",
      "marks": 70.67,
      "totalMarks": 100,
      "attempted": 53,
      "totalQs": 65,
      "correct": 46,
      "incorrect": 7,
      "notAttempted": 12,
      "duration": "180 Min",
      "timeTaken": "169m",
      "accuracy": "87%",
      "notes": "",
      "tags": [],
      "difficulty": "77",
      "session": "afternoon"
    },
    {
      "id": "1784718601564",
      "folderId": "gate",
      "title": "GATE CSE 2015 | Set 3 | Original Paper",
      "date": "2026-08-12",
      "marks": 71.33,
      "totalMarks": 100,
      "attempted": 52,
      "totalQs": 65,
      "correct": 48,
      "incorrect": 4,
      "notAttempted": 13,
      "duration": "180 Min",
      "timeTaken": "180m",
      "accuracy": "92%",
      "notes": "",
      "tags": [],
      "difficulty": "74",
      "session": "afternoon"
    },
    {
      "id": "1784718601565",
      "folderId": "gate",
      "title": "GATE CSE 2016 | Set 1 | Original Paper",
      "date": "2026-08-13",
      "marks": 68.33,
      "totalMarks": 100,
      "attempted": 58,
      "totalQs": 65,
      "correct": 49,
      "incorrect": 9,
      "notAttempted": 7,
      "duration": "180 Min",
      "timeTaken": "179m",
      "accuracy": "84%",
      "notes": "",
      "tags": [],
      "difficulty": "72",
      "session": "afternoon"
    },
    {
      "id": "1784718601566",
      "folderId": "gate",
      "title": "GATE CSE 2016 | Set 2 | Original Paper",
      "date": "2026-08-14",
      "marks": 75.66,
      "totalMarks": 100,
      "attempted": 60,
      "totalQs": 65,
      "correct": 50,
      "incorrect": 10,
      "notAttempted": 5,
      "duration": "180 Min",
      "timeTaken": "169m",
      "accuracy": "83%",
      "notes": "",
      "tags": [],
      "difficulty": "74",
      "session": "afternoon"
    },
    {
      "id": "1784718601590",
      "folderId": "nptel",
      "title": "Mock Test - 16.08.2026 - NPTEL",
      "date": "2026-08-16",
      "marks": 62,
      "totalMarks": 97,
      "attempted": 57,
      "totalQs": 66,
      "correct": 44,
      "incorrect": 13,
      "notAttempted": 9,
      "duration": "180 Min",
      "timeTaken": "0.00 Min",
      "accuracy": "77%",
      "notes": "",
      "tags": [
        "NPTEL",
        "Mock Test"
      ],
      "difficulty": "",
      "session": ""
    },
    {
      "id": "1784718601580",
      "folderId": "go_classes",
      "title": "GO Classes CS Test Series | Algorithms | Topic Wise Test 1",
      "date": "2026-08-17",
      "marks": 14.67,
      "totalMarks": 25,
      "attempted": 15,
      "totalQs": 15,
      "correct": 10,
      "incorrect": 5,
      "notAttempted": 0,
      "duration": "45 Min",
      "timeTaken": "42.77 Min",
      "accuracy": "67%",
      "notes": "",
      "tags": [
        "Algorithms",
        "Topic Wise"
      ],
      "difficulty": "",
      "session": ""
    },
    {
      "id": "1784718601581",
      "folderId": "go_classes",
      "title": "GO Classes CS Test Series | Algorithms | Topic Wise Test 2",
      "date": "2026-08-17",
      "marks": 12,
      "totalMarks": 25,
      "attempted": 11,
      "totalQs": 15,
      "correct": 8,
      "incorrect": 3,
      "notAttempted": 4,
      "duration": "45 Min",
      "timeTaken": "43.15 Min",
      "accuracy": "73%",
      "notes": "",
      "tags": [
        "Algorithms",
        "Topic Wise"
      ],
      "difficulty": "",
      "session": ""
    },
    {
      "id": "1784718601567",
      "folderId": "gate",
      "title": "GATE CSE 2017 | Set 1 | Original Paper",
      "date": "2026-08-19",
      "marks": 72.66,
      "totalMarks": 100,
      "attempted": 57,
      "totalQs": 65,
      "correct": 48,
      "incorrect": 9,
      "notAttempted": 8,
      "duration": "180 Min",
      "timeTaken": "180m",
      "accuracy": "84%",
      "notes": "",
      "tags": [],
      "difficulty": "64",
      "session": "afternoon"
    },
    {
      "id": "1784718601568",
      "folderId": "gate",
      "title": "GATE CSE 2017 | Set 2 | Original Paper",
      "date": "2026-08-24",
      "marks": 72.66,
      "totalMarks": 100,
      "attempted": 59,
      "totalQs": 65,
      "correct": 49,
      "incorrect": 10,
      "notAttempted": 6,
      "duration": "180 Min",
      "timeTaken": "179m",
      "accuracy": "83%",
      "notes": "",
      "tags": [],
      "difficulty": "66",
      "session": "afternoon"
    },
    {
      "id": "1784718601569",
      "folderId": "gate",
      "title": "GATE CSE 2018 | Original Paper",
      "date": "2026-09-04",
      "marks": 58.67,
      "totalMarks": 100,
      "attempted": 52,
      "totalQs": 65,
      "correct": 43,
      "incorrect": 9,
      "notAttempted": 13,
      "duration": "180 Min",
      "timeTaken": "180m",
      "accuracy": "83%",
      "notes": "",
      "tags": [],
      "difficulty": "85",
      "session": "afternoon"
    },
    {
      "id": "1784718601570",
      "folderId": "gate",
      "title": "GATE CSE 2019 | Original Paper",
      "date": "2026-09-09",
      "marks": 72,
      "totalMarks": 100,
      "attempted": 60,
      "totalQs": 65,
      "correct": 50,
      "incorrect": 10,
      "notAttempted": 5,
      "duration": "180 Min",
      "timeTaken": "177m",
      "accuracy": "83%",
      "notes": "",
      "tags": [],
      "difficulty": "72",
      "session": "afternoon"
    },
    {
      "id": "1784718601571",
      "folderId": "gate",
      "title": "GATE CSE 2020 | Original Paper",
      "date": "2026-09-17",
      "marks": 77.67,
      "totalMarks": 100,
      "attempted": 59,
      "totalQs": 65,
      "correct": 53,
      "incorrect": 6,
      "notAttempted": 6,
      "duration": "180 Min",
      "timeTaken": "176m",
      "accuracy": "90%",
      "notes": "",
      "tags": [],
      "difficulty": "68",
      "session": "afternoon"
    }
  ]
};
